name: sdassistant
description: Utility to share content with services

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  grpc: ^2.1.2
  protobuf: ^1.0.0
  multicast_dns: ^0.2.2
  file_picker: ^1.4.0
  quiver: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true